import Testing
import Foundation
@testable import faBolus

/// Safety-disable consent dialogs must not leak the stale `§13-DRAFT` clinical-review marker, and
/// first-run onboarding must surface `RegulatoryCopy.firstRun` so the experimental framing is on
/// the actual first-run screen.
@Suite struct SafetyCopyGuardTests {

    /// Exact stale draft-marker prefix this scan forbids.
    static let staleDraftMarker = "§13-DRAFT — pending Phase 10 clinical review"

    /// Walk up from `#filePath` until `project.yml` is found.
    private static func repoRootURL() -> URL? {
        let fm = FileManager.default
        var probe = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = probe.appendingPathComponent("project.yml")
            if fm.fileExists(atPath: candidate.path) { return probe }
            probe = probe.deletingLastPathComponent()
        }
        return nil
    }

    private static func sourceText(relativeTo root: URL, path: String) throws -> String {
        let url = root.appendingPathComponent(path)
        return try String(contentsOf: url, encoding: .utf8)
    }

    @Test func notificationSettingsViewNoLongerCarriesStaleDraftMarker() throws {
        guard let root = Self.repoRootURL() else {
            Issue.record("SafetyCopyGuardTests could not resolve repo root — scan would pass vacuously")
            return
        }
        let source = try Self.sourceText(relativeTo: root, path: "ios/faBolus/Views/NotificationSettingsView.swift")
        #expect(!source.isEmpty, "NotificationSettingsView.swift read as empty — scan would pass vacuously")
        #expect(
            !source.contains(Self.staleDraftMarker),
            "NotificationSettingsView.swift still carries the stale clinical-review draft-marker prefix (§13 is recorded cleared — this is leaked internal process jargon)"
        )
    }

    @Test func connectPumpOnboardingViewSurfacesFirstRunRegulatoryCopy() throws {
        guard let root = Self.repoRootURL() else {
            Issue.record("SafetyCopyGuardTests could not resolve repo root — scan would pass vacuously")
            return
        }
        let source = try Self.sourceText(relativeTo: root, path: "ios/faBolus/Views/ConnectPumpOnboardingView.swift")
        #expect(!source.isEmpty, "ConnectPumpOnboardingView.swift read as empty — scan would pass vacuously")
        #expect(
            source.contains("RegulatoryCopy.firstRun"),
            "ConnectPumpOnboardingView.swift does not surface RegulatoryCopy.firstRun — the first-run experimental/not-FDA-cleared framing is missing from the actual first-run screen"
        )
    }

    /// The pump-mirror settings section must label its source as the pump (Decision 1c) — a mirrored
    /// alert must never read as generated by faBolus itself.
    @Test func notificationSettingsViewLabelsPumpMirrorAlertsAsComingFromThePump() throws {
        guard let root = Self.repoRootURL() else {
            Issue.record("SafetyCopyGuardTests could not resolve repo root — scan would pass vacuously")
            return
        }
        let source = try Self.sourceText(relativeTo: root, path: "ios/faBolus/Views/NotificationSettingsView.swift")
        #expect(!source.isEmpty, "NotificationSettingsView.swift read as empty — scan would pass vacuously")
        #expect(
            source.contains("mirrored from your pump's own alarms"),
            "the pump-mirror section must label the source as the pump (Decision 1c)"
        )
        #expect(
            !source.contains("always critical-severity"),
            "the retired claim that pump alarms always break through Focus/DND must not still be in the settings copy — pump alarms now default to Alert, not Urgent (D-10)"
        )
    }

    /// The first-run disclosure's breakthrough copy is best-effort ("when allowed"), never a promise
    /// ("will") — Decision 3 — and stays consistent with the ladder's capability-hidden Urgent rung.
    @Test func notificationDisclosureViewUsesBestEffortBreakthroughCopyNeverAPromise() throws {
        guard let root = Self.repoRootURL() else {
            Issue.record("SafetyCopyGuardTests could not resolve repo root — scan would pass vacuously")
            return
        }
        let source = try Self.sourceText(relativeTo: root, path: "ios/faBolus/Views/NotificationDisclosureView.swift")
        #expect(!source.isEmpty, "NotificationDisclosureView.swift read as empty — scan would pass vacuously")
        #expect(
            source.contains("when allowed"),
            "the first-run disclosure's breakthrough copy must be best-effort (\"when allowed\"), never a promise (Decision 3)"
        )
        #expect(
            !source.contains("will break through") && !source.contains("will always break through"),
            "the first-run disclosure must never promise breakthrough will happen"
        )
    }

    /// The decorative hero antenna glyph on the first-run pump-connect screen must be
    /// `.accessibilityHidden(true)` so VoiceOver does not announce its raw SF Symbol name. Windowed
    /// after the symbol so an unrelated `.accessibilityHidden` elsewhere cannot satisfy it.
    @Test func connectPumpOnboardingViewHidesDecorativeHeroIcon() throws {
        guard let root = Self.repoRootURL() else {
            Issue.record("SafetyCopyGuardTests could not resolve repo root — scan would pass vacuously")
            return
        }
        let source = try Self.sourceText(relativeTo: root, path: "ios/faBolus/Views/ConnectPumpOnboardingView.swift")
        #expect(!source.isEmpty, "ConnectPumpOnboardingView.swift read as empty — scan would pass vacuously")
        guard let symbolRange = source.range(of: "antenna.radiowaves.left.and.right") else {
            Issue.record(
                "ConnectPumpOnboardingView.swift no longer contains the hero antenna glyph — this guard's anchor is stale and would pass vacuously"
            )
            return
        }
        // Modifier chain follows the Image on the next few lines; a short window keeps the assertion
        // bound to the hero icon rather than the whole file.
        let window = source[symbolRange.upperBound...].prefix(200)
        #expect(
            window.contains(".accessibilityHidden(true)"),
            "ConnectPumpOnboardingView.swift's decorative hero antenna icon is not .accessibilityHidden(true) — VoiceOver would announce its raw SF Symbol name"
        )
    }
}
